/**
 * GameActions - Centralized action types for the FarmSim reducer
 */
export const GAME_ACTIONS = {
    // Core game actions
    SET_COINS: 'SET_COINS',
    SET_XP: 'SET_XP',
    SET_LEVEL: 'SET_LEVEL',

    // Plot management
    UPDATE_PLOT: 'UPDATE_PLOT',
    UPDATE_PLOTS: 'UPDATE_PLOTS',
    SET_GRID_SIZE: 'SET_GRID_SIZE',

    // Inventory
    UPDATE_INVENTORY: 'UPDATE_INVENTORY',

    // Weather
    SET_WEATHER: 'SET_WEATHER',
    UPDATE_WEATHER_FORECAST: 'UPDATE_WEATHER_FORECAST',

    // Buildings
    UPDATE_BUILDINGS: 'UPDATE_BUILDINGS',

    // Livestock
    UPDATE_LIVESTOCK: 'UPDATE_LIVESTOCK',

    // Fishing
    UPDATE_FISHING: 'UPDATE_FISHING',

    // Achievements
    UPDATE_ACHIEVEMENTS: 'UPDATE_ACHIEVEMENTS',

    // Collections
    UPDATE_COLLECTIONS: 'UPDATE_COLLECTIONS',

    // Seasonal events
    SET_SEASONAL_EVENTS: 'SET_SEASONAL_EVENTS',
    UPDATE_ACTIVE_EVENTS: 'UPDATE_ACTIVE_EVENTS',

    // Daily challenges
    SET_DAILY_CHALLENGES: 'SET_DAILY_CHALLENGES',
    UPDATE_CHALLENGE_PROGRESS: 'UPDATE_CHALLENGE_PROGRESS',

    // Daily quests
    UPDATE_DAILY_QUESTS: 'UPDATE_DAILY_QUESTS',
    UPDATE_WEEKLY_CONTRACTS: 'UPDATE_WEEKLY_CONTRACTS',

    // Disaster protections
    UPDATE_DISASTER_PROTECTIONS: 'UPDATE_DISASTER_PROTECTIONS',

    // Prestige
    UPDATE_PRESTIGE: 'UPDATE_PRESTIGE',
    PRESTIGE_RESET: 'PRESTIGE_RESET',

    // Research
    UPDATE_RESEARCH: 'UPDATE_RESEARCH',

    // Genetics
    UPDATE_GENETICS: 'UPDATE_GENETICS',

    // Social
    UPDATE_SOCIAL: 'UPDATE_SOCIAL',

    // Notifications
    ADD_NOTIFICATION: 'ADD_NOTIFICATION',
    CLEAR_NOTIFICATION: 'CLEAR_NOTIFICATION',

    // Season
    UPDATE_SEASON: 'UPDATE_SEASON',

    // UI state
    SET_SELECTED_CROP: 'SET_SELECTED_CROP',
    SET_DECORATE_MODE: 'SET_DECORATE_MODE',
    SET_DECORATE_TOOL: 'SET_DECORATE_TOOL',
    SET_SELECTED_DECORATION: 'SET_SELECTED_DECORATION',
    SET_MOVING_DECORATION: 'SET_MOVING_DECORATION',
    UPDATE_DECORATIONS: 'UPDATE_DECORATIONS',

    // Game settings
    UPDATE_SETTINGS: 'UPDATE_SETTINGS',
    UPDATE_AUTOMATION: 'UPDATE_AUTOMATION',

    // Performance
    UPDATE_GAME_LOOP: 'UPDATE_GAME_LOOP',

    // Pets
    UPDATE_PETS: 'UPDATE_PETS',

    // Processing
    UPDATE_PROCESSING_FACILITIES: 'UPDATE_PROCESSING_FACILITIES',
    UPDATE_PROCESSING_QUEUE: 'UPDATE_PROCESSING_QUEUE',
    UPDATE_PROCESSED_INVENTORY: 'UPDATE_PROCESSED_INVENTORY',

    // Save/Load
    LOAD_GAME: 'LOAD_GAME',
};

export default GAME_ACTIONS;
