/**
 * GameActions - Centralized action types for the FarmSim reducer
 */
export const GAME_ACTIONS = {
    // Core game actions
    SET_COINS: 'SET_COINS',
    SET_XP: 'SET_XP',
    SET_LEVEL: 'SET_LEVEL',

    // Plot management
    UPDATE_PLOT: 'UPDATE_PLOT',
    UPDATE_PLOTS: 'UPDATE_PLOTS',
    SET_GRID_SIZE: 'SET_GRID_SIZE',

    // Inventory
    UPDATE_INVENTORY: 'UPDATE_INVENTORY',

    // Weather
    SET_WEATHER: 'SET_WEATHER',
    UPDATE_WEATHER_FORECAST: 'UPDATE_WEATHER_FORECAST',

    // Buildings
    UPDATE_BUILDINGS: 'UPDATE_BUILDINGS',

    // Livestock
    UPDATE_LIVESTOCK: 'UPDATE_LIVESTOCK',

    // Fishing
    UPDATE_FISHING: 'UPDATE_FISHING',

    // Achievements
    UPDATE_ACHIEVEMENTS: 'UPDATE_ACHIEVEMENTS',
    UPDATE_MEMORY_FLAGS: 'UPDATE_MEMORY_FLAGS',
    UPDATE_MEMORY_COUNTERS: 'UPDATE_MEMORY_COUNTERS',
    UPDATE_ALMANAC: 'UPDATE_ALMANAC',
    SET_PHILOSOPHY: 'SET_PHILOSOPHY',
    UPDATE_COZY_GOALS: 'UPDATE_COZY_GOALS',
    UPDATE_WHATS_NEW: 'UPDATE_WHATS_NEW',
    SET_FARM_NAME: 'SET_FARM_NAME',
    SET_FARM_THEME: 'SET_FARM_THEME',
    SET_SPOTLIGHT: 'SET_SPOTLIGHT',
    SET_LAST_UNLOCKED_MEMORY: 'SET_LAST_UNLOCKED_MEMORY',
    SET_LAST_UNLOCKED_ALMANAC: 'SET_LAST_UNLOCKED_ALMANAC',
    UPDATE_COZY_EXPANSION: 'UPDATE_COZY_EXPANSION',
    SET_ACTIVE_FARM_TITLE: 'SET_ACTIVE_FARM_TITLE',

    // Seasonal events
    SET_SEASONAL_EVENTS: 'SET_SEASONAL_EVENTS',
    UPDATE_ACTIVE_EVENTS: 'UPDATE_ACTIVE_EVENTS',

    // Daily challenges
    SET_DAILY_CHALLENGES: 'SET_DAILY_CHALLENGES',
    UPDATE_CHALLENGE_PROGRESS: 'UPDATE_CHALLENGE_PROGRESS',
    UPDATE_CHALLENGE_STREAK: 'UPDATE_CHALLENGE_STREAK',
    UPDATE_LAST_CHALLENGE_RESET: 'UPDATE_LAST_CHALLENGE_RESET',

    // Daily quests
    UPDATE_DAILY_QUESTS: 'UPDATE_DAILY_QUESTS',

    // Disaster protections
    UPDATE_DISASTER_PROTECTIONS: 'UPDATE_DISASTER_PROTECTIONS',

    // Mini-games
    UPDATE_MINIGAMES: 'UPDATE_MINIGAMES',

    // Prestige
    UPDATE_PRESTIGE: 'UPDATE_PRESTIGE',
    PRESTIGE_RESET: 'PRESTIGE_RESET',

    // Research
    UPDATE_RESEARCH: 'UPDATE_RESEARCH',

    // Genetics
    UPDATE_GENETICS: 'UPDATE_GENETICS',

    // Social
    UPDATE_SOCIAL: 'UPDATE_SOCIAL',

    UPDATE_MILESTONES: 'UPDATE_MILESTONES',
    UPDATE_GHOST_VISIT: 'UPDATE_GHOST_VISIT',
    SET_SEED_PROVENANCE: 'SET_SEED_PROVENANCE',

    // Notifications
    ADD_NOTIFICATION: 'ADD_NOTIFICATION',
    CLEAR_NOTIFICATION: 'CLEAR_NOTIFICATION',
    CLEAR_NOTIFICATION_HISTORY: 'CLEAR_NOTIFICATION_HISTORY',

    // Season
    UPDATE_SEASON: 'UPDATE_SEASON',

    // UI state
    SET_SELECTED_CROP: 'SET_SELECTED_CROP',
    SET_SELECTED_DECORATION: 'SET_SELECTED_DECORATION',
    SET_DECORATION_MODE: 'SET_DECORATION_MODE',
    UPDATE_ENTITLEMENTS: 'UPDATE_ENTITLEMENTS',
    SET_PREMIUM_LOCK_PROMPT: 'SET_PREMIUM_LOCK_PROMPT',

    // Game settings
    UPDATE_SETTINGS: 'UPDATE_SETTINGS',

    // Performance
    UPDATE_GAME_LOOP: 'UPDATE_GAME_LOOP',

    // Onboarding
    UPDATE_ONBOARDING: 'UPDATE_ONBOARDING',

    // Retention
    UPDATE_RETENTION: 'UPDATE_RETENTION',

    // Pets
    UPDATE_PETS: 'UPDATE_PETS',

    // Processing
    UPDATE_PROCESSING_FACILITIES: 'UPDATE_PROCESSING_FACILITIES',
    UPDATE_PROCESSING_QUEUE: 'UPDATE_PROCESSING_QUEUE',
    UPDATE_PROCESSED_INVENTORY: 'UPDATE_PROCESSED_INVENTORY',

    // Save/Load
    LOAD_GAME: 'LOAD_GAME',
};

export default GAME_ACTIONS;
